### ISSUE TITLE
Nullable check should terminate further assertions for nullable null

### ISSUE THREAD

**Issue by scaytrase** [lezhnev74/openapi-psr7-validator#12]
At this point if `$this->schema->nullable === true` and `$this->data === null` we should terminate any futher checks since there is no sence to check any keyword on null which is valid if schema is nullable

https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Validator.php#L68

**Comment by scaytrase** [comment]
I'll try to provide PR for this ASAP

**Comment by lezhnev74** [comment]
Good point! It makes total sense.
Let me review the PR now.
