### ISSUE TITLE
Validation returns OperationAddress - just wondering why?

### ISSUE THREAD

**Issue by judgej** [lezhnev74/openapi-psr7-validator#17]
I'm trying a simple bit of validation:

```php
$myJsonSpec = '{...}';
$serverRequest = // PSR-7 message constructed by hand
$validator = \OpenAPIValidation\PSR7\ServerRequestValidator::fromJson($myJsonSpec);
$result = $validator->validate($serverRequest);
```
If all validates correctly I get this object returned:

`OpenAPIValidation\PSR7\OperationAddress`

For example:

```php
object(OpenAPIValidation\PSR7\OperationAddress)#47 (2) {
  ["method":protected]=>
  string(3) "get"
  ["path":protected]=>
  string(15) "/ccodes/{ccode}"
}
```

The method and the path are keys to the operation, so I'm wondering whether it would be more useful to return the operation? The `operationId` could then be used to fire off further parsing of the server request (I'm looking at generated code to do this). I may be missing the reason for returning `OperationAddress` though.

Without knowing the `operationId` at this point, further work needs to be done to decode the method and path to find it. It may already be available somewhere I'm not just looking.

Also, the `validate()` method either returns this object, or throws an exception. The exception is just for one of what may be many validation errors. Is there a way to find all the validation errors rather than just reporting on one? Looking at the validator, I can see it scatters `_errors` across many of the nodes of its internal data structures, so I'm guessing it does scan for multiple validation errors at once.

**Comment by judgej** [comment]
The "constructed by hand" PSR-7 message, just for interest, is done like this:

```php
// composer require http-interop/http-factory-guzzle

// Payload
$data = [...];

$serverRequestFactory = new \Http\Factory\Guzzle\ServerRequestFactory();
$streamFactory = new \Http\Factory\Guzzle\StreamFactory();
$serverRequest = $serverRequestFactory->createServerRequest('GET', 'https://example.com/ccodes/C12345');
$serverRequest = $serverRequest->withHeader('Content-Type', 'application/json');
$serverRequest = $serverRequest->withBody($streamFactory->createStream(json_encode($data)));
```

**Comment by lezhnev74** [comment]
Great question. Shortly, the ServerRequestValidator returns OperationAddress, so you can easily feed it to the `ResponseValidator` on the next step. See how it is done in the middleware here: https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR15/ValidationMiddleware.php#L87

1. Request can match to any operation (path/method) in the spec.
2. `ServerRequestValidator` will tell you which operation matched the request.
3. So then you can take this information and validate response against this operation.
4. I assume that the package should hide internal details and not return cebe's `Operation` instance. Instead, it should operate with its own objects.

**Comment by judgej** [comment]
Okay, that makes more sense. Where I'm coming from is integration into Laravel and Lumen apps. That has its own routing, which can run in a number of different ways, but *usually* each route will be passed to a controller method to handle.

Laravel request middleware usually does one of several things: throws an exception on a bad request, redirects to a login page, or processes the request to add something of its own that the controller can use.

So I think I would be looking more to separating some of these concerns to bolt them in at various points. I would be happy to let the request go all the way through to the controller. The validation in the request middleware would validate, and then pass the request to a parser to turn it into a bunch of nested value objects (*probably*) built separately from the OpenAPI 3.0 spec. Those would get tagged onto the request and so the controller would be able to use them.

The response (*probably*) does not need to be validated, but if it did, that would happen on the outgoing pipeline (can't remember what that is called. How that is passed the operation ID and/or request method and path, I'm not sure.

I'm new to a lot of this API stuff, so there may be better ways to structure the application, but that's where we are at the moment, using what we know.

In short, I'm looking for a validator to validate the server request, but not to get involved in turning it into a response. However, it needs to supply enough information to be able to fire the correct validation for the response as it pops out the other side of the controller. Hope that makes sense.

If I'm using your validator for both validations, then taking the `OperationAddress` spat out by the request validator and feeding it into the response validator *whereever that is* (and how, being my problem) is exactly what I need here for validation. Parsing the request body is the tricky bit, but again if that is able to accept the `OperationAddress` to decode, then it should be doable. I'll need to build the decoder for that into the generated payload parser - unless the `OperationAddress` can include the `OperationId` as a property. `Validator::findOperationSpec()` could give me a step towards that, but it's private:

```php
// This would be awesome:
$operationAddress = $serverRequestValidator->validate($serverRequest);
$operationSpec = $serverRequestValidator->findOperationSpec($operationAddress);
var_dump($operationSpec->operationId);
// string(8) "getCcode" <<-- I can use this to tell the request parser what to look for
```

**Comment by lezhnev74** [comment]
Ok, I see that you want to build this validation logic into your workflow. I understand that it can be hard.

There are some assumptions in the package:
- it should do just two things (basically): validate ServerRequest, validate Response
- it should hide all the internal details as much as possible (so if you need to make do something special, you'd better fork it and play with it on your own). I understand that it would be nice to be able to get some internal state and read directly, but it goes in contradiction with general encapsulation ideas. If you want to hack it in, fork it.
- upcoming changes will highly likely change the API of the package to make it more granular, tweakable etc.

Again, I completely understand your desire to fit this package in your workflow the way you want it. I'll keep in mind this desire while iterating over the package API.

**Comment by judgej** [comment]
I'm not sure it is internal state I need at all. It is a view into the request that I am looking for. The HTTP request is fixed at this point - the state is not changing, and I am not changing it in the package.

I look forward to the more granular approach. Everything I need is there, but like LEGO, I would like to be able to pieces the blocks together in a slightly different order, with my own LEGO blocks in between some of the steps.

It is great that this package can handle an entire API server layer with nothing more than a PSR-7/PSR-18 implementation added, and some hooks to the code behind the APIs. A lot of what it does will also be extremely useful in frameworks that also tackle *some* of that stuff already, and this is where I'm coming from. Before I fork and play, I'd like to try to convince you that this package can be the best of both worlds :-)

**Comment by lezhnev74** [comment]
@scaytrase looking at your recent PR #16, what are your thoughts about the points raised by @judgej?

**Comment by scaytrase** [comment]
From my point of view there is no crime in returning matched operation if validation passed. But It might be better to return some kind of `ValidationResult` instead, with internal enrichment. This also whould allow to collect validation data for multiple matched operations (if all of them fail).

But from other side I agree with @judgej for some points, i.e

you have multiple matched operations and validator selects first while framework router selects other (both might be valid!) but second one has different response signature (i.e, different schemas for different business logic values). This might lead to response validation errors.

more robust would be to validate response against `anyOf` valid operation or utilize external info about really matched route

**Comment by lezhnev74** [comment]
> more robust would be to validate response against anyOf valid operation 

Well, this makes total sense to me. Indeed, the request can match multiple operations (kind of an edge case, but still).

**Comment by scaytrase** [comment]
Some concerns about comlexity and performance here, though

**Comment by lezhnev74** [comment]
After recent changes we introduced:
- validators builder
- access the schema after the validation (see https://github.com/lezhnev74/openapi-psr7-validator#reuse-schema-after-validation)

@judgej do you think it can simplify your workflow?

**Comment by judgej** [comment]
I'll certainly give it a go :-)

**Comment by scaytrase** [comment]
I think we should create second validation like `RoutedRequestValidator` which will accept `OperationAddress` on the input as `ResponseValidator` do and will do no additional path matching (aka routing) for project where routing occurs with framework or other tools

**Comment by lezhnev74** [comment]
Sounds good! Can you elaborate on that and use-cases?

**Comment by scaytrase** [comment]
sure

**Comment by scaytrase** [comment]
https://github.com/lezhnev74/openapi-psr7-validator/pull/43/commits/b47e4abdf7482a538bdfedaa1dc9385b46ca40cc

very simple implementation, I think it can make things much easier
