### ISSUE TITLE
Exceptions consistency

### ISSUE THREAD

**Issue by scaytrase** [lezhnev74/openapi-psr7-validator#18]
Here I will create a list of inconsistent exceptions or exception hierarchy:

 - [x]  (https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Keywords/Type.php#L113)[FormatMismatch] exception is derived from `\LogicException`, which according [to the manual](https://www.php.net/manual/en/class.logicexception.php) happens only if code logic is broken and there is a bug or misbehaviour in the library
 - [x] Same stands for `ValidationKeywordFailed`
 - [x] I'm not sure there is sense in catching any `\Throwable` since it too broad (i.e it would catch `\ParseError` and convert it to `KeywordValidationFailed` too)
 - [ ] Most other exceptions are derived from `\RuntimeException`, like `MissedRequestCookie`
 - [ ] `MultipleOperationsMismatchForRequest` extends `Exception` this looks correct but misaligned with other exceptions :)

Notes: `\LogicException` and `\RuntimeException` are kind of ["Unchecked exceptions"](https://crunchify.com/better-understanding-on-checked-vs-unchecked-exceptions-how-to-handle-exception-better-way-in-java/) analogue in PHP and they are often [excluded from IDE static analisys by default](https://blog.jetbrains.com/phpstorm/2018/04/configurable-unchecked-exceptions/)

**Comment by digilist** [comment]
It would be great if all exceptions can implement one interface, so that it's easy to catch all Open API validation related exceptions :blush:

**Comment by scaytrase** [comment]
@digilist You can see the proposed PR. All PSR-7 validation exceptions now inherit `ValidationFailed` and it's strictly fixed within the validators signature. For schema matching they are already inherit `SchemaMismatch` root exception

**Comment by digilist** [comment]
Sorry, you are right. Didn't see the open PR. Thank you!
