### ISSUE TITLE
Invalid invalid type handling

### ISSUE THREAD

**Issue by scaytrase** [lezhnev74/openapi-psr7-validator#19]
If data type does not match schema code still tries to utilize it as a scalar value. moreother it tries utilize value itself rather than type, and this can lead to huge error texts

```
notice: "Array to string conversion in /data/www/content.leos.lamoda.ru/vendor/lezhnev74/openapi-psr7-validator/src/Schema/Keywords/Type.php on line 81"
```

I'll try to fix it

**Comment by scaytrase** [comment]
Also some questions @lezhnev74 

https://github.com/lezhnev74/openapi-psr7-validator/blob/aa1cef2c9592e9c2b5e63edc77e5fde2d72ea8fe/src/Schema/Keywords/Type.php#L70

This line should some kind of schema validation step, not data validation. It's rather strange to decline data here if schema is invalid. Probably this should go to `cebe/php-openapi` instead

https://github.com/lezhnev74/openapi-psr7-validator/blob/aa1cef2c9592e9c2b5e63edc77e5fde2d72ea8fe/src/Schema/Keywords/Type.php#L67

counting data befor validating its type is unsafe (especially for php 7.2). why we expecting items in data at all?

**Comment by scaytrase** [comment]
Also schema validation is duplicated here

https://github.com/lezhnev74/openapi-psr7-validator/blob/aa1cef2c9592e9c2b5e63edc77e5fde2d72ea8fe/src/Schema/Keywords/Type.php#L49

and here 

https://github.com/lezhnev74/openapi-psr7-validator/blob/aa1cef2c9592e9c2b5e63edc77e5fde2d72ea8fe/src/Schema/Keywords/Type.php#L90

I hope we can leave second only, it's more obvious

**Comment by lezhnev74** [comment]
Great points! 

1. `$this->parentSchema->items`. 
Agree, this is too defensive. This should be delegated to the underlying package.
2. `count($data) && ! (is_array($data) && ArrayHelper::isAssoc($data))`
This must make sure that the data is an array, and it has no string keys (which makes it a dictionary in terms of JSON). What would be a better check here? Ah, I jsut saw the PR. This code solves the problem: `if (! is_array($data) || ArrayHelper::isAssoc($data)) {...`
3. `Also schema validation is duplicated here`.
Agreed. Let's leave just `switch` statement here. Again, sometimes my code is over defensive.

**Comment by scaytrase** [comment]
2. everything but counting is ok. counting is unsafe and really not needed. to check vector against array `is_array($data) && !ArrayHelper::isAssoc($data)` is enough. Counting on non countable would fail in 7.2+

https://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

**Comment by scaytrase** [comment]
For 1 and 3 I can update #21 removing these additional checks

**Comment by lezhnev74** [comment]
Please, go ahead, sounds good!

**Comment by scaytrase** [comment]
Done. Raised one more question in PR
