### ISSUE TITLE
Improve Testing with Mermade/openapi3-examples

### ISSUE THREAD

**Issue by philsturgeon** [lezhnev74/openapi-psr7-validator#2]
If you'd like more example documents to improve your testing, this is an amazing resource: https://github.com/Mermade/openapi3-examples.

**Comment by lezhnev74** [comment]
Exactly what I was looking for (to try various use cases). 
Thank you!

**Comment by cebe** [comment]
there are two more resources in https://github.com/cebe/php-openapi/issues/21
