### ISSUE TITLE
Handle JSON:API's application/vnd.api+json content type

### ISSUE THREAD

**Issue by osteel** [lezhnev74/openapi-psr7-validator#26]
Hi,

I'm currently trying out your package to run functional tests against an OpenAPI schema in a Laravel application.

We're following the [JSON:API](https://jsonapi.org/) specification for our API, meaning the `Content-Type` and `Accept` headers are expected to be `application/vnd.api+json`.

But in the [`Body` validator](https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/Validators/Body.php#L42), the body will only be JSON-decoded if the `Content-Type` header is `application/json`.

Would it be possible to change the regex to also handle `application/vnd.api+json`?

Or are we expected to extend this behaviour somehow?

I'd also like to seize this opportunity to thank you for you work and encourage you to push it further - this is definitely headed in the right direction and very much needed by the PHP community!

Thanks,

Yannick

**Comment by lezhnev74** [comment]
Hi Yannick, this is a great question!

There are many possible media types which describe JSON payload. This tool should detect such occasions. At the moment you can't easily extend it and change how validation works, so I'll push a fix for this [JSON-API](https://jsonapi.org/) media type: `application/vnd.api+json`.

This media type `application/vnd.api+json` can look differently, for example, [Github uses](https://developer.github.com/v3/media/) something like this: `application/vnd.github.version.param+json`.

I think this regex should do the trick: `^application\/.*json$` ([check online](https://www.regextester.com/?fam=109554))

**Comment by lezhnev74** [comment]
`0.13.2` is tagged. Let me know if this is still an issue.

**Comment by osteel** [comment]
@lezhnev74 it is not! I get the expected behaviour now.

Thanks for the quick response! 👍
