### ISSUE TITLE
Composite validation rules' related exceptions are lost

### ISSUE THREAD

**Issue by osteel** [lezhnev74/openapi-psr7-validator#27]
Hi,

The [`InvalidSchema`](https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Exception/InvalidSchema.php) exception (and maybe others) will only display the wrapping error and omit the related ones when the error is a composite one (such as [Respect/Validation](https://github.com/Respect/Validation)'s [`AllOf`](https://github.com/Respect/Validation/blob/master/library/Rules/AllOf.php)).

The issue with this is we don't know what the errors actually are, which makes it really hard to troubleshoot, e.g:

```
OpenAPIValidation\PSR7\Exception\Response\ResponseBodyMismatch: OpenAPI spec does not match the body of the response [/api/test,get,200]: Schema(or data) validation failed: All of the required rules must pass for "{\"data\":\"test\"}"
```

This doesn't tell you what the actual (related) exceptions are.

Hope that makes sense!

Thanks,

Yannick

**Comment by lezhnev74** [comment]
Another great catch, Yannick! 
Exceptions are not really self-explanatory (partially because the validation package that is used does not give good messages). The messages clarity is definitely something to be improved in the upcoming releases.

Let me meditate on this problem for some time. 

@scaytrase what do you think?

**Comment by scaytrase** [comment]
I think that invalid schema should not be explanatory. it's defensive exception and validation of given schema is not a job of this lib

**Comment by scaytrase** [comment]
For other exceptions there is a tradeof of performance and completeness. I.e there we can validate every schema  for allof after first invalid, but this would waste time. I think we can make this optional, at least for schema namespace

**Comment by osteel** [comment]
Hi guys, thanks for your replies.

> partially because the validation package that is used does not give good messages

I think it does actually, by way of the related exceptions as can be seen [here](https://github.com/Respect/Validation/blob/1.1/library/Rules/AllOf.php#L27) for example, in the `allOf` class.

> it's defensive exception and validation of given schema is not a job of this lib

I hear your argument, and I agree. However I'm not sure we're talking about _validating_ the schema here, we're really comparing the response's format to the format that is described in the schema. It seems to me that's the purpose of this package: test whether the response respects the schema.

In my case, I had to dump the exceptions [here](https://github.com/Respect/Validation/blob/1.1/library/Rules/AllOf.php#L26) before they're passed on to `setRelated` to understand what was going on, and I got this:

```
"{\"data\":\"test\"}" must be of the type array
```

That's how I understood the response was considered an array by default, and that I had to specify `type: object` in my schema.

The schema itself was valid (I made sure of that by running [cebe's CLI tool](https://github.com/cebe/php-openapi#cli-tool) on the schema both with and without the `type` attribute), but the response did not match it. Hence I'm not sure why it ended up being an `InvalidSchema` exception in the first place?

I obviously could be missing something here!

If not, the message above indeed being the result of an assertion that failed, in my opinion it should be printed along with the more generic error.

Or at the very least, it should be available for the software that uses your package to retrieve it and display it if necessary.

I think these composite exceptions all extend the [NestedValidationException](https://github.com/Respect/Validation/blob/1.1/library/Exceptions/NestedValidationException.php) class, meaning the related exceptions can be retrieved via the [`getRelated`](https://github.com/Respect/Validation/blob/1.1/library/Exceptions/NestedValidationException.php#L243) method (or maybe just the [`getMessages`](https://github.com/Respect/Validation/blob/1.1/library/Exceptions/NestedValidationException.php#L201) method).

So maybe your package's exceptions could hold them as well?

**Comment by scaytrase** [comment]
> In my case, I had to dump the exceptions here before they're passed on to setRelated to understand what was going on, and I got this:

Looks like a bug. Just a bug.

I think we mixed up schema checks and data check somewhere. Data checks should not throw `InvalidSchema`, neither use Respect validations. I hope this should be catched by `type` keyword validator but did not for some reason. I think you can submit a simple test to reproduce it, or the whole fix if you want. @lezhnev74 WDYT ?

**Comment by scaytrase** [comment]
I see two data checks, but they look defensive to - one for `Items` (checks that items are array indeed, but this should be checked with `type` keyword check beforehand) and one for `Properties` (checks that data is hash to search property in). So it looks like a bug in validation order or check structure.

If you give us minimal schema and data sample causing this, I think we can debug this.

**Comment by osteel** [comment]
Hmm this is a bit embarrassing, I can't seem to replicate the issue anymore. When I strip it down to a very simple example it doesn't make a difference whether I specify `type: object` or not, and in the bigger schema (the actual one used by the app we're building) removing `type` doesn't cause an issue anymore either.

But we changed the schema quite a bit since yesterday so we might have removed what was causing it incidentally.

I'm gonna close this for now, and might reopen if I manage to replicate, in which case I'll post the schema. Thanks again for your help
