### ISSUE TITLE
Tries to validate content even if no content was specified

### ISSUE THREAD

**Issue by osteel** [lezhnev74/openapi-psr7-validator#28]
Hi,

When deleting a resource and the response has no content, the `ResponseValidator` still tries to [validate the body](https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/ResponseValidator.php#L63):
```
// 2. Validate Body
try {
    $bodyValidator = new Body();
    $bodyValidator->validate($response, $spec->content);
} catch (Throwable $e) {
    ...
```
If my OAS response is defined like this:
```
delete:
  summary: Delete a resource
  responses:
    '204':
      description: No content
```
In the previous code sample `$spec->content` is an empty array.

The `Body` validator subsequently [tries to get the `Content-Type` header](https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/Validators/Body.php#L29) which doesn't exist, and throws a `NoContentType` exception.

I think the whole body validation should be skipped if no content's been defined in the OAS specification (which is valid as per [Swagger's doc](https://swagger.io/docs/specification/describing-responses/#empty)).

**EDIT:** Or maybe still check whether there's a body despite the fact that no content was specified in the OAS spec, which I guess should throw an exception.

**Comment by lezhnev74** [comment]
Wow, great catch! 

According to [HTTP rfc2616#section-7.2.1](https://tools.ietf.org/search/rfc2616#section-7.2.1) the body is indeed optional, as well as the header `Content-Type`. 

This case must be addressed by this package (I'll write a patch to fix this).

P.s. to think through:
- no-header does not mean no-body
- no-body does not mean no-header
- so, header and body can be present/missing at any combinations (according to the RFC).

**Comment by lezhnev74** [comment]
I made a minor fix. Tagged `0.13.3`. Let me know if this helped.

**Comment by osteel** [comment]
@lezhnev74 it did help - thanks for the fix!

Although now any response with no content defined in the OAS spec will pass the body validator check, while we might expect the package to test whether the response body actually is empty when the OAS spec indicates it should be the case (no `content` defined).

But maybe you're already planning to do this and this was just a quick fix for now - in any case, I let you decide whether to close this issue now or later :)

Thanks again!

**Comment by lezhnev74** [comment]
> Although now any response with no content defined in the OAS spec will pass the body validator check

This is a good point. If a schema does not set any expectations on what the body should look like, it won't validate at all. In other words, I am not sure if `no content keyword` means `empty body`. To me, it means `I don't know what body should look like, I don't care`.

@scaytrase wanna join the discussion?

**Comment by scaytrase** [comment]
Yeah, sounds interesting. I think, headers should add restrictions on body content. In other words the body should match headers, no matters which (we can even create extensible body-header matcher). If there is `content-type` header - body should be of this content type. If there is `content-length` - content should be of this length, etc. If there is no headers - no validation should occure.

> To me, it means I don't know what body should look like, I don't care

so yes, something like this.
