### ISSUE TITLE
Validator ignores base uri path

### ISSUE THREAD

**Issue by scaytrase** [lezhnev74/openapi-psr7-validator#3]
Given openapi spec with 
   Server base uri `http://localhost:8000/api/v1`
   POST operation `/products.create`

I expect POST request `http://localhost:8000/api/v1/products.create` to be valid

Actual result
```
OpenAPI spec contains no such operation [/api/v1/products.create,post]
```

```
        $yaml = /** @lang yaml */
            <<<YAML
openapi: 3.0.0
info:
  title: Product import API
  version: '1.0'
servers:
  - url: 'http://localhost:8000/api/v1'
paths:
  /products.create:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                test:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  result: 
                    type: string
YAML;

        $validator = new ServerRequestValidator(CebeReader::readFromYaml($yaml));

        $psrRequest = new ServerRequest(
            'POST',
            'http://localhost:8000/api/v1/products.create'
        );

        $validator->validate($psrRequest);
```

According to https://swagger.io/docs/specification/api-host-and-base-path/ having base url path prefix is totally valid

**Comment by lezhnev74** [comment]
Good catch! Ill fix it asap. Now focusing on `security` keyword.

**Comment by lezhnev74** [comment]
@scaytrase I've completed first iteration over base uri feature.
Your test looks green now: https://github.com/lezhnev74/openapi-psr7-validator/blob/master/tests/FromCommunity/ScayTraseTest.php

I noticed that you did not add `type:object` before `properties`. I thought that was a violation of OAS 3.

**Comment by cebe** [comment]
> I noticed that you did not add `type:object` before `properties`. I thought that was a violation of OAS 3.

the spec does not mention this explicitly anywhere, but tools tend to assume type `object` when `properties` is specified.

**Comment by scaytrase** [comment]
assume or require? i validate my schema against https://editor.swagger.io, so they should be pretty valid, but it's interesting question anyway

**Comment by lezhnev74** [comment]
I've removed this check. I was applying "defensive programming" and wanted to protect the code from unexpected side effects.

**Comment by lezhnev74** [comment]
I'll allocate some time for testing different `servers` values, gonna close this one once confirmed that it works as expected.

**Comment by scaytrase** [comment]
Yeah, I've just updated to 0.7 and this looks like fixed at the moment
