### ISSUE TITLE
"Required" option for header parameters is ignored

### ISSUE THREAD

**Issue by TarasBK** [lezhnev74/openapi-psr7-validator#30]
Request validator ignores "required" option for header parameters, and treats all such parameters as mandatory, opposed to OpenAPI Specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject.

required | boolean | Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.
-- | -- | --

**Comment by lezhnev74** [comment]
Thank you for the report!
I need some time to check it.

**Comment by lezhnev74** [comment]
The bug is confirmed! I've pushed a new patch with a corresponding test: `\OpenAPIValidationTests\PSR7\PathParametersTest::testItAllowsOptionalParametersGreen`
Tagged `0.13.4`

Let me know if the problem resolved for you.

**Comment by TarasBK** [comment]
Thanks, the problem is resolved!
