### ISSUE TITLE
Relative paths in servers objects

### ISSUE THREAD

**Issue by TarasBK** [lezhnev74/openapi-psr7-validator#32]
When url field in server object containts relative path, for example "/v2" or "/", validator can't match request with operation definition.

For example, if we have definition:
``` yaml
servers:
  - url: '/v1'
paths:
  /operations:
    post:
...
```
and try to validate POST request "http://localhost/v1/operations", we get an exception "OpenAPI spec contains no such operation [/operations,post]". But if we specify server url as "http://localhost/v1", everything works fine.

If I understand it correctly, there is no possibility to match any request, when server path is relative (or if "servers" section is omitted altogether, and default value is one server with url="/").

From OpenAPI documentaion it is not very clear what to do in this case
https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#serverObject
> The URLs in the servers array can be relative, such as /v2. In this case, the URL is resolved against the server that hosts the given OpenAPI definition.

Should validator ignore server name from request, when path is relative? Or somehow get "server that hosts the given OpenAPI definition" and match it to server name from request?

Do you have any suggestions?

**Comment by lezhnev74** [comment]
>Should validator ignore server name from request, when path is relative?

This is one way. Another would be letting the package know server's URI. So the package can substitute any relative URLs with `schema://host` of the current server. That aligns with OpenAPI documentation. 

From the top of my head, this code illustrates the approach:
```php
$validator = (new ValidatorBuilder())
                ->fromYamlFile($this->apiSpecFile)
                ->setServerHost('https://localhost')
                ->getServiceRequestValidator();

$validator->validate($request);
```

**Comment by lezhnev74** [comment]
I've made a PR with a patch. It works, but I am not sure about the code design.

@cebe can you jump into the discussion for a moment and review this code snippet here: https://github.com/lezhnev74/openapi-psr7-validator/pull/33/files#diff-932afa69f5c86fa663a6d7724fd1af21R140 (lines 140-157)

I am actually changing an instance of `\cebe\openapi\spec\OpenApi`, however it has its properties marked as `* @property-read Server[] $servers`.

**Comment by TarasBK** [comment]
> > Should validator ignore server name from request, when path is relative?
> 
> This is one way. Another would be letting the package know server's URI. So the package can substitute any relative URLs with `schema://host` of the current server. That aligns with OpenAPI documentation.

For our project first way would have been more preferable. Nevertheless looking forward to any solution.

**Comment by dmytro-demchyna** [comment]
Hi, @lezhnev74 .
I think the "servers" block is intended not for validation purposes at all. It uses by client software to discover the server URL for request sending.  Good example - button "Try it out" in Swagger UI (https://petstore.swagger.io/). If openapi-psr7-validator will validate the "servers",  backend developers will get problems. Specially if the application is containerized (Docker, etc) and developers don't know on which hosts (availability zones, staging, a/b testing, etc) admins will expose it.

**Comment by lezhnev74** [comment]
@scaytrase what do you think?
@dmytro-demchyna are you suggesting not validating hostname at all?

**Comment by scaytrase** [comment]
well, I can agree with this validation is not useful, but not sure we should validate nothing at all.

currently we use relative paths as well as docker images and we have no problems with validation. I think that if server urls are specified - this is intentional and communication should not occure on other hosts. If any host is allowed - relative URL is an option

**Comment by dmytro-demchyna** [comment]
> Should validator ignore server name from request, when path is relative?

It is the best solution in my opinion, because it allows to use relative path for developers that don't want to care about hosts. To my thinking OpenAPI documentation tells same:

> The URLs in the servers array can be relative, such as /v2. In this case, the URL is resolved against the server that hosts the given OpenAPI definition.

So, we can place the definition to any server

**Comment by cebe** [comment]
> Or somehow get "server that hosts the given OpenAPI definition" and match it to server name from request?

if you want to do that you could get that information from `ReferenceContext` class in case the spec is not loaded from a local file.

> I am actually changing an instance of `\cebe\openapi\spec\OpenApi`, however it has its properties marked as `* @property-read Server[] $servers`.

This is wrong annotation, I forgot to change `@property-read` to `@property` when I implemented changing of the properties and writing possibility. Will be changed in next release.

> So the package can substitute any relative URLs with `schema://host` of the current server.

This makes more sense. If you make a request to the API there must be a webserver configured to resolve the request so we can assume the hostname to be valid without looking into the spec.
I'd also vote against using server array for validation, it should be used by clients to find possible API endpoints, but not limit the valid API endpoints to thoses specified in the spec.

**Comment by lezhnev74** [comment]
Ok, I am going to go along with NOT validating hostnames at all.
It makes total sense to me that `servers` are used by API clients to discover API hosts and NOT for validation.

**Comment by lezhnev74** [comment]
Reverted the previously proposed solution and pushed a new patch.
This test shows the new approach: [`tests/PSR7/ServerRequestRelativeServerTest.php`](https://github.com/lezhnev74/openapi-psr7-validator/blob/4b1276c530132e09965b2ef640e0a0fa9b1db15f/tests/PSR7/ServerRequestRelativeServerTest.php)

tagged `0.13.6`
