### ISSUE TITLE
Validating non string query parameters

### ISSUE THREAD

**Issue by NullNinja1** [lezhnev74/openapi-psr7-validator#36]
Hello,

I'm trying to validate a request containing two query parameters.

![image](https://user-images.githubusercontent.com/20226134/60525080-a6b78680-9ce5-11e9-9359-3a9d1146c795.png)

Upon doing so i am receiving a RequestQueryArgumentMismatch due to the query arguments of the request not being a type 'integer', and a 'string' given.

As of version 3.0 of openapi, query parameters can be specified as an integer along with other non string data types, i would have thought the PSR-7 validator would be able to look at a query parameter and check if it is an integer within a string.

https://swagger.io/docs/specification/describing-parameters/

**Comment by judgej** [comment]
Since query parameters are always going to be presented by the request object as strings, the validation is different to how it would be performed on a JSON payload with its many data types. I guess validation even for integers, floats, doubles etc. would just be about pattern matching.

If scientific notation is accepted as valid number formats, then it gets even more complicated, so I'm not going there ;-)

**Comment by lezhnev74** [comment]
Yeah, good question! It makes sense to validate types as OpenAPI specification allows us describing it in details. However as @judgej points out, it can be a nontrivial thing.

**Comment by lezhnev74** [comment]
After some considerations I am adding this type juggling from string->integer and similar.

**Comment by cebe** [comment]
it's actually not really type juggling but deserialisation. If you think about this as two steps involved:

1. deserialize request parameter following what is in the spec
2. validate the result

in case of an integer the deserialization would fail if it is not numeric.

> If scientific notation is accepted as valid number formats, then it gets even more complicated, so I'm not going there ;-)

It's more easy in case of PHP, you could check for `is_numeric($value)` :)

**Comment by lezhnev74** [comment]
Added these rules:
- `type:boolean` matches case insensitive `true` or `false`
- `type:number` matches both integers and floats with/without signs
- `type:integer` matches numbers consisted of numbers only with an optional sign

**Comment by NullNinja1** [comment]
> Added these rules:
> 
> * `type:boolean` matches case insensitive `true` or `false`
> * `type:number` matches both integers and floats with/without signs
> * `type:integer` matches numbers consisted of numbers only with an optional sign

Thank you for adding this! I am testing the changes now. :)

**Comment by lezhnev74** [comment]
If nothing comes up, I am going to tag this evening.

**Comment by NullNinja1** [comment]
> If nothing comes up, I am going to tag this evening.

Tested the changes again with the same query parameters and it is now validating the request correctly with no exceptions. :)

**Comment by lezhnev74** [comment]
tagged `0.13.9`
