### ISSUE TITLE
Library does not play well with references

### ISSUE THREAD

**Issue by scaytrase** [lezhnev74/openapi-psr7-validator#4]
Given schema with reference and valid JSON input

```
        $yaml = /** @lang yaml */
            <<<'YAML'
openapi: 3.0.0
info:
  title: Product import API
  version: '1.0'
servers:
  - url: 'http://localhost:8000'
paths:
  /products.create:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                test: 
                  $ref: "#/components/schemas/TestObject" 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  result: 
                    type: string
components:
  schemas:
    TestObject:
      type: object
      required:
        - input
      properties:
        input:
          type: string
          example: 5201f887-e28a-45df-ad93-bde1021bae11
YAML;

        $cebeSchema = CebeReader::readFromYaml($yaml);
        $validator = new ServerRequestValidator($cebeSchema);

        $psrRequest = new ServerRequest(
            'POST',
            'http://localhost:8000/products.create',
            [
                'Content-Type' => 'application/json',
            ],
            <<<JSON
{
    "test": {
        "input": "some data"
    }
}
JSON
        );


            $validator->validate($psrRequest);
```

I expect validator to pass this object.

Actual results: 

```
OpenAPI spec does not match the body of the request [/products.create,post]: All of the required rules must pass for { "test": `[object] (cebe\openapi\spec\Reference: { })` }
```

Because of https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Keywords/Properties.php#L64
(each validator has this line)

If I comment out these lines and add the following hack

```patch
        $cebeSchema = CebeReader::readFromYaml($yaml);
+       $cebeSchema->setReferenceContext(new ReferenceContext($cebeSchema, '/'));
        $validator = new ServerRequestValidator($cebeSchema);
```

And add 
```
            if ($schema instanceof Reference) {
                $schema = $schema->resolve();
            }
```
To each validator this starts working better, but it ends up here

https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Keywords/Required.php#L61

since property could be a reference to a schema, not a real property.

Manually resolving all references before validation helps. but this looks too complicated to end user to know about manual references resolution

```patch
        $cebeSchema = CebeReader::readFromYaml($yaml);
        $cebeSchema->setReferenceContext(new ReferenceContext($cebeSchema, '/'));
+        $cebeSchema->resolveReferences();
        $validator = new ServerRequestValidator($cebeSchema);
```

**Comment by lezhnev74** [comment]
Yeah, when I first thought about that, I wanted to avoid working with references and just resolve them all in the first place. For example, [speccy](https://github.com/wework/speccy) did it in my projects:
```
speccy resolve file.yaml
```

Though I see the point in doing it automatically. Let me meditate on this for a while...

**Comment by scaytrase** [comment]
In our case we generate schema (with zircote lib) programmatically to supply it to api conaumers and also use the same schema in order to validate request, so it's hard to utilize external tools. but since there is a workaround we can treat this as an usability issue

**Comment by lezhnev74** [comment]
Will work on this one asap

**Comment by lezhnev74** [comment]
Pushed `0.10.0` which does auto-resolving of dependencies

**Comment by scaytrase** [comment]
I've updated to latest 0.11.1 and this one looks resolved with new factory methods `::fromYaml` which does internal auto-resolution.

Thank you!

**Comment by lezhnev74** [comment]
Good! Let me know if anything else pops up.
