### ISSUE TITLE
multipart with fields without content type won't pass validation

### ISSUE THREAD

**Issue by imefisto** [lezhnev74/openapi-psr7-validator#49]
In #44 support for multipart request was improved. If you send fields with files (which have content-type), it works ok. But if a field without content type is included, an exception will be thrown:

```
Message: preg_match() expects parameter 2 to be string, null given
File: /app/vendor/lezhnev74/openapi-psr7-validator/src/PSR7/Validators/BodyValidator/MultipartValidator.php
Line: 178
```
Added a quick fix in [fork](https://github.com/imefisto/openapi-psr7-validator/tree/bugfix/handle-no-file-fields-on-multipart)

**Comment by scaytrase** [comment]
Would you mind open a PR?
