### ISSUE TITLE
Automatically casts numeric strings to integer even if spec says it's a string

### ISSUE THREAD

**Issue by Aaronmacaron** [lezhnev74/openapi-psr7-validator#62]
This issue is closely related to #58 . 

I have a path parameter that is a string. Though, if I pass a string that is numeric such as `"123"` you automatically cast it to an integer: 

https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/PSR7/OperationAddress.php#L98

This leads to the validation failing because the parameter is expected to be a string but it isn't because you cast it to an integer.

You should probably check if the specification says that the parameter is a string and if so don't cast it to an integer.

**Comment by lezhnev74** [comment]
Good catch! 
Yeah, URLs serialize anything as a string, deserialization is not so straightforward. Probably optimistic casting to int is not the perfect solution.

**Comment by lezhnev74** [comment]
Well, I've prepared a small patch which removes the casting feature (which is "too smart"). 
I can't remember why it was introduced in the first place though.

**Comment by Aaronmacaron** [comment]
Great! I think this resolves my problem. Thanks for the quick solution.

When do you think this will be merged/released?

**Comment by lezhnev74** [comment]
I am expecting some extra feedback from @scaytrase If nothing pops up today, I think I'll tag `0.16`

**Comment by lezhnev74** [comment]
Tagged. Did it help?

**Comment by Aaronmacaron** [comment]
Yep. It solved my problem. Thank you :+1:
