### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by philsturgeon** [lezhnev74/openapi-psr7-validator#65]
Hey there! I think there is a great chance for you folks to collaborate here. I am opening up the conversation here as it has the most stars, but it could be anywhere. They are all good implementations.

- @mieszkomalawski - https://gitlab.com/mmalawski/openapi-validator
- @hkarlstrom - https://github.com/hkarlstrom/openapi-validation-middleware

These packages all do the same thing. 

1. Read a JSON or YAML file
2. Allow general PSR-7/PSR-15 middleware to be created for this file
3. Offer at least request validation (maybe response too)
4. Offer errors in various formats (RFC 7807 or others)
5. Support [custom formats](https://github.com/lezhnev74/openapi-psr7-validator#custom-type-formats)

I think you could all team up on a new @thephpleague project. I bet they'd take you if you all worked together, I can provide some guidance if needed, and then you just archive things on GitHub, mark them abandoned on Packagist, and the mega-package lives on forever despite whatever hurdles life throw at you individually. 

LMK if you like the sound of this. OpenAPI can be just too much for single maintainers to handle solo. 🤷‍♂

**Comment by lezhnev74** [comment]
It is a smart move to have a single project for this type of problems run by the community (instead of pouring efforts in many projects). The league seems to be a perfect place for that kind of activity. This package is licensed under MIT so there are no problems to use it for starting a project on the league foundation. 
I am not archiving this, but if such transition happens I'll add a banner to this repo that a community edition (which is better) is available on the league repo.

**Comment by mieszkomalawski** [comment]
+1 to this

Having one quality package under league umbrella sounds great. BTW I will have a presentation this week about OpenAPI and validation at https://summit.phpers.pl/pl/

**Comment by hkarlstrom** [comment]
+1

**Comment by philsturgeon** [comment]
This is great! I poked my friend Frank De Jonge who is still active with the league:

> Sounds like a good fit. I'll start off the conversation on this end. In the meanwhile, if they can join the slack channel, that'd speed thing up and make it easy to communicate: slack.thephpleague.com

**Comment by cebe** [comment]
> These packages all do the same thing.
> 
> 1. Read a JSON or YAML file

There is also duplicated effort here:

- [hkarlstrom/openapi-validation-middleware](https://github.com/hkarlstrom/openapi-validation-middleware) uses [hkarlstrom/openapi-reader](https://github.com/hkarlstrom/openapi-reader)
- [mmalawski/openapi-validator](https://gitlab.com/mmalawski/openapi-validator) seems to have its own implementation
- lezhnev74/openapi-psr7-validator (this package) uses [cebe/php-openapi](https://github.com/cebe/php-openapi) (created by me)

Happy to participate in the collaboration.

**Comment by brayniverse** [comment]
You're all great! I'm so happy to see you all talking about collaborating.

My team and I were investigating ways to test API results against our API spec and had to downgrade from OpenAPI 3 to Swagger 2 because OpenAPI 3 wasn't as widely supported. I can't remember which implementation we landed on, but I'd be excited to migrate to a common implementation that all you bright developers are contributing to. I'd love to help however I can.

**Comment by lezhnev74** [comment]
@hkarlstrom what's your email, just want to get in touch about this project?

**Comment by lezhnev74** [comment]
![image](https://user-images.githubusercontent.com/10206110/65211859-924f8280-dab9-11e9-9ad2-7e3082d0294a.png)

**Comment by lezhnev74** [comment]
Thank you guys!
It has happened. 
Go to https://github.com/thephpleague/openapi-psr7-validator

**Comment by scaytrase** [comment]
Congrats! Do we have any roadmap? Also can we transfer current significant issues to the new project?

**Comment by lezhnev74** [comment]
Yes, I did migrate some of them. 
Feel free to add the rest that you feel needs to be done.

**Comment by philsturgeon** [comment]
This is amazing, thank you @lezhnev74, and thank you @mieszkomalawski and @hkarlstrom for all working together on this! I can't wait to see one awesome super validator be the best of all three implementations.

**Comment by philsturgeon** [comment]
Btw @hkarlstrom could you move some of your feature requests over? 

https://github.com/hkarlstrom/openapi-validation-middleware/issues/33
https://github.com/hkarlstrom/openapi-validation-middleware/issues/27

**Comment by hkarlstrom** [comment]
Sure, will do it tmr!

**Comment by scaytrase** [comment]
I think we should also mark packages (https://packagist.org/packages/lezhnev74/openapi-psr7-validator) as abandoned with suggested replacement in order to make users transit to new one
